//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cld.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_lg
    {
        public int id { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> act_date { get; set; }
        public byte[] act_time { get; set; }
        public string module { get; set; }
    }
}
